kind = "web"
previewPath = "/"
title = "Smart Hostel Leave & Outpass System"
version = "1.0.0"
id = "artifacts/hostel-outpass"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 21744

[services.development]
run = "pnpm --filter @workspace/hostel-outpass run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/hostel-outpass", "run", "build" ]
publicDir = "artifacts/hostel-outpass/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "21744"
BASE_PATH = "/"
